{% set name = "pytest-repeat" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cd3289745ab3156d43eb9c8e7f7d00a926f3ae5c9cf425bec649b2fe15bad5b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - pytest >=3.6

test:
  files:
    - test_repeat.py
  commands:
    # Make sure to fail pytest on unknown markers
    # this will ensure that pytest fails if pytest-repeat isn't registered
    - pytest -Werror test_repeat.py

about:
  home: https://github.com/pytest-dev/pytest-repeat/
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE
  summary: pytest-repeat is a plugin for py.test that makes it easy to repeat a single test, or multiple tests, a specific number of times.

extra:
  recipe-maintainers:
    - hmaarrfk
